/**
 * reviewStatus three rules, against the shape an invalid broadcast leaves
 * behind: transactions.status still unproven, proven_tx_reqs.status = invalid,
 * the generated output still spendable, and the allocated input still held.
 */
import { DatabaseSync } from 'node:sqlite'
import {
  LIVE_OFFLINE_SKIP_TXIDS_SQL,
  REVIEW_OUTPUTS_SQL,
  failInvalidReqTxs,
  reviewStatusOnDb
} from '../../core/storage/methods/reviewStatusSql'

const TX1 = 'aa'.repeat(32)
const TX2 = 'bb'.repeat(32)

function seeded(): DatabaseSync {
  const d = new DatabaseSync(':memory:')
  d.exec(`
    CREATE TABLE transactions (transactionId INTEGER PRIMARY KEY, txid TEXT, status TEXT, provenTxId INTEGER);
    CREATE TABLE proven_tx_reqs (provenTxReqId INTEGER PRIMARY KEY, txid TEXT, status TEXT);
    CREATE TABLE outputs (outputId INTEGER PRIMARY KEY, transactionId INTEGER, spendable INTEGER, spentBy INTEGER);
    CREATE TABLE offline_actions (offlineActionId INTEGER PRIMARY KEY, txid TEXT, status TEXT);
  `)
  return d
}

/** Tx 1 unproven + invalid req; output A generated by it; output B allocated as its input. */
function seedInvalidUnproven(d: DatabaseSync): void {
  d.prepare('INSERT INTO transactions VALUES (1, ?, ?, ?)').run(TX1, 'unproven', null)
  d.prepare('INSERT INTO transactions VALUES (2, ?, ?, ?)').run(TX2, 'completed', null)
  d.prepare('INSERT INTO proven_tx_reqs VALUES (1, ?, ?)').run(TX1, 'invalid')
  d.exec('INSERT INTO outputs VALUES (1, 1, 1, NULL)')
  d.exec('INSERT INTO outputs VALUES (2, 2, 0, 1)')
}

const spendables = (d: DatabaseSync) =>
  d.prepare('SELECT outputId, spendable, spentBy FROM outputs ORDER BY outputId').all() as {
    outputId: number
    spendable: number
    spentBy: number | null
  }[]

const txStatus = (d: DatabaseSync, id: number) =>
  (d.prepare('SELECT status FROM transactions WHERE transactionId = ?').get(id) as { status: string }).status

describe('reviewStatusOnDb', () => {
  it('fails the invalid-req tx, unspends its output, and restores its allocated input', () => {
    const d = seeded()
    seedInvalidUnproven(d)

    const r = reviewStatusOnDb(d, { skipTxids: new Set() })

    expect(txStatus(d, 1)).toBe('failed')
    expect(txStatus(d, 2)).toBe('completed')
    expect(spendables(d)).toEqual([
      { outputId: 1, spendable: 0, spentBy: null },
      { outputId: 2, spendable: 1, spentBy: null }
    ])
    expect(r.log).not.toBe('')
  })

  it.each(['queued', 'posting'] as const)('does not change a tx with a %s offline_action', status => {
    const d = seeded()
    seedInvalidUnproven(d)
    d.prepare('INSERT INTO offline_actions (txid, status) VALUES (?, ?)').run(TX1, status)
    const skipTxids = new Set(
      (d.prepare(LIVE_OFFLINE_SKIP_TXIDS_SQL).all() as { txid: string }[]).map(row => row.txid)
    )

    const r = reviewStatusOnDb(d, { skipTxids })

    expect(txStatus(d, 1)).toBe('unproven')
    expect(spendables(d)).toEqual([
      { outputId: 1, spendable: 1, spentBy: null },
      { outputId: 2, spendable: 0, spentBy: 1 }
    ])
    expect(r.log).toBe('')
  })

  it('does not restore inputs of a failed tx whose req is still in flight', () => {
    const d = seeded()
    seedInvalidUnproven(d)
    d.exec("UPDATE transactions SET status = 'failed' WHERE transactionId = 1")
    d.prepare('UPDATE proven_tx_reqs SET status = ? WHERE txid = ?').run('unsent', TX1)

    reviewStatusOnDb(d, { skipTxids: new Set() })

    expect(spendables(d)).toEqual([
      { outputId: 1, spendable: 1, spentBy: null },
      { outputId: 2, spendable: 0, spentBy: 1 }
    ])
  })

  it('does not fail a completed transaction that has an invalid req', () => {
    const d = seeded()
    d.prepare('INSERT INTO transactions VALUES (1, ?, ?, ?)').run(TX1, 'completed', 99) // provenTxId 99
    d.prepare('INSERT INTO proven_tx_reqs VALUES (1, ?, ?)').run(TX1, 'invalid')
    reviewStatusOnDb(d, { skipTxids: new Set() })
    expect(txStatus(d, 1)).toBe('completed')
  })
})

describe('REVIEW_OUTPUTS_SQL', () => {
  it('excludes outputs that cannot change', () => {
    const d = seeded()
    d.exec('INSERT INTO outputs VALUES (1, 1, 0, NULL)')
    d.exec('INSERT INTO outputs VALUES (2, 1, 1, NULL)')
    d.exec('INSERT INTO outputs VALUES (3, 1, 0, 9)')
    const rows = d.prepare(REVIEW_OUTPUTS_SQL).all() as { outputId: number }[]
    expect(rows.map(r => r.outputId)).toEqual([2, 3])
  })
})

describe('failInvalidReqTxs', () => {
  it('continues after fail() throws on one row', async () => {
    const seen: number[] = []
    const r = await failInvalidReqTxs({
      rows: [{ transactionId: 1, txid: 'aa' }, { transactionId: 2, txid: 'bb' }],
      skipTxids: new Set(),
      fail: async id => {
        seen.push(id)
        if (id === 1) throw new Error('already completed')
      }
    })
    expect(seen).toEqual([1, 2])
    expect(r.failed).toBe(1)
    expect(r.skipped).toBe(1)
  })
})
