/**
 * The three reviewStatus rules, as SQL against a SQLite handle.
 *
 * Mirrors reviewStatusIdb: fail txs whose proven_tx_req is invalid; restore
 * inputs allocated to a terminal-failed spender; mark outputs generated by a
 * terminal-failed tx unspendable.
 *
 * skipTxids (live queued/posting offline_actions) are left untouched so a
 * still-in-flight offline send is not failed out from under the queue.
 */

import { devLog } from '../../logging'

const SAFE_REQ_STATUSES = new Set(['invalid', 'doubleSpend'])

export type ReviewStatusDb = {
  prepare(sql: string): {
    all: (...params: unknown[]) => unknown[]
    run: (...params: unknown[]) => unknown
  }
}

export const LIVE_OFFLINE_SKIP_TXIDS_SQL = `
  SELECT txid FROM offline_actions
  WHERE status IN ('queued','posting') AND txid IS NOT NULL AND txid <> ''
`.trim()

export const REVIEW_INVALID_REQ_TXS_SQL = `
  SELECT t.transactionId, t.txid, t.status
  FROM transactions t
  JOIN proven_tx_reqs r ON r.txid = t.txid
  WHERE r.status = 'invalid' AND t.status <> 'failed' AND t.provenTxId IS NULL AND t.status <> 'completed'
`.trim()

export const REVIEW_FAILED_TXS_SQL = `SELECT transactionId, txid FROM transactions WHERE status = 'failed'`

export const REVIEW_REQ_STATUSES_SQL = `SELECT status FROM proven_tx_reqs WHERE txid = ?`

export const REVIEW_OUTPUTS_SQL = `SELECT outputId, transactionId, spendable, spentBy FROM outputs`

const FAIL_TX_SQL = `UPDATE transactions SET status = 'failed' WHERE transactionId = ?`
const RESTORE_INPUT_SQL = `UPDATE outputs SET spendable = 1, spentBy = NULL WHERE outputId = ?`
const UNSPEND_OUTPUT_SQL = `UPDATE outputs SET spendable = 0, spentBy = NULL WHERE outputId = ?`

export type ReviewFailedTx = { transactionId: number; txid?: string | null }
export type ReviewOutput = {
  outputId: number
  transactionId: number
  spendable: number | boolean
  spentBy?: number | null
}

export async function failInvalidReqTxs(args: {
  rows: { transactionId: number; txid: string | null }[]
  skipTxids: Set<string>
  fail: (transactionId: number) => Promise<void>
}): Promise<{ failed: number; skipped: number }> {
  let failed = 0
  let skipped = 0
  const seen = new Set<number>()
  for (const row of args.rows) {
    if (seen.has(row.transactionId)) continue
    seen.add(row.transactionId)
    if (row.txid && args.skipTxids.has(row.txid)) {
      skipped++
      continue
    }
    try {
      await args.fail(row.transactionId)
      failed++
    } catch (e) {
      skipped++
      devLog(
        `[reviewStatus] could not fail transaction ${row.transactionId}:`,
        e instanceof Error ? e.message : e
      )
    }
  }
  return { failed, skipped }
}

/** Failed txs whose reqs are all invalid/doubleSpend (or missing) are safe to restore against. */
export function collectFailedTransactionIds(
  failedTxs: ReviewFailedTx[],
  reqStatusesByTxid: Map<string, string[]>,
  skipTxids: Set<string>
): { failedTransactionIds: Set<number>; safeFailedTransactionIds: Set<number> } {
  const failedTransactionIds = new Set<number>()
  const safeFailedTransactionIds = new Set<number>()
  for (const tx of failedTxs) {
    if (tx.txid && skipTxids.has(tx.txid)) continue
    failedTransactionIds.add(tx.transactionId)
    let hasBlockingReq = false
    if (tx.txid != null && tx.txid !== '') {
      const reqs = reqStatusesByTxid.get(tx.txid) ?? []
      hasBlockingReq = reqs.some(status => !SAFE_REQ_STATUSES.has(status))
    }
    if (!hasBlockingReq) safeFailedTransactionIds.add(tx.transactionId)
  }
  return { failedTransactionIds, safeFailedTransactionIds }
}

export function outputReviewAction(
  output: ReviewOutput,
  failedTransactionIds: Set<number>,
  safeFailedTransactionIds: Set<number>
): 'restore' | 'unspend' | undefined {
  const generatedByFailedTx = failedTransactionIds.has(output.transactionId)
  const generatedBySafeFailedTx = safeFailedTransactionIds.has(output.transactionId)
  const spentBySafeFailedTx = output.spentBy != null && safeFailedTransactionIds.has(output.spentBy)
  if (spentBySafeFailedTx && !generatedByFailedTx) return 'restore'
  if (generatedBySafeFailedTx && (Boolean(output.spendable) || output.spentBy != null)) return 'unspend'
  return undefined
}

export function reviewStatusOnDb(db: ReviewStatusDb, opts: { skipTxids: Set<string> }): { log: string } {
  const { skipTxids } = opts
  let log = ''

  const seenFail = new Set<number>()
  const invalid = db.prepare(REVIEW_INVALID_REQ_TXS_SQL).all() as {
    transactionId: number
    txid: string | null
    status: string
  }[]
  const failStmt = db.prepare(FAIL_TX_SQL)
  for (const tx of invalid) {
    if (seenFail.has(tx.transactionId)) continue
    seenFail.add(tx.transactionId)
    if (tx.txid && skipTxids.has(tx.txid)) continue
    log += `transaction ${tx.transactionId} updated to status of 'failed' was ${tx.status}\n`
    failStmt.run(tx.transactionId)
  }

  const failedTxs = db.prepare(REVIEW_FAILED_TXS_SQL).all() as ReviewFailedTx[]
  const reqStatusesByTxid = new Map<string, string[]>()
  const reqStmt = db.prepare(REVIEW_REQ_STATUSES_SQL)
  for (const tx of failedTxs) {
    if (tx.txid == null || tx.txid === '' || reqStatusesByTxid.has(tx.txid)) continue
    const reqs = reqStmt.all(tx.txid) as { status: string }[]
    reqStatusesByTxid.set(
      tx.txid,
      reqs.map(row => row.status)
    )
  }
  const { failedTransactionIds, safeFailedTransactionIds } = collectFailedTransactionIds(
    failedTxs,
    reqStatusesByTxid,
    skipTxids
  )

  const restoreStmt = db.prepare(RESTORE_INPUT_SQL)
  const unspendStmt = db.prepare(UNSPEND_OUTPUT_SQL)
  const outputs = db.prepare(REVIEW_OUTPUTS_SQL).all() as ReviewOutput[]
  for (const output of outputs) {
    const action = outputReviewAction(output, failedTransactionIds, safeFailedTransactionIds)
    if (action === 'restore') {
      restoreStmt.run(output.outputId)
      log += `output ${output.outputId} updated to spendable because spentBy is failed\n`
    } else if (action === 'unspend') {
      unspendStmt.run(output.outputId)
      log += `output ${output.outputId} updated to not spendable because transaction is failed\n`
    }
  }

  return { log }
}
